autyzm-pg/friendly-plans-react

src/models/PlanItem.tsx, src/screens/runPlan/PlanItemName.tsx, src/screens/runPlan/PlanItemTimer.tsx, src/screens/runPlan/runPlanList/PlanItemListItem.tsx, src/screens/runPlan/runPlanSlide/PlanSlideItem.tsx, src/screens/updatePlanItem/PlanItemTimer.tsx
If time for a task is set, it is displayed in child mode next to task name
Timer counts down until it reaches 0.
Timer for the next task starts when the previos task is completed.
=> #29 handle timer

src/screens/dashboard/StudentPlanListItem.tsx, src/screens/runPlan/PlanItemName.tsx, src/screens/runPlan/PlanItemTimer.tsx, src/screens/runPlan/runPlanList/PlanItemListItem.tsx, src/screens/studentSettings/SlideCardSwitch.tsx, src/screens/updatePlan/PlanHeader.tsx, src/screens/updatePlan/UpdatePlanScreen.tsx, src/screens/updatePlanItem/PlanItemTimer.tsx
Added circle-play icon in update plan item screen that navigates to child mode 
+ when checking child display setting changed to use consts from Student model
=> Resolves #41 run plan from edit view

src/models/PlanElement.ts, src/models/PlanItem.tsx, src/models/PlanSubItem.ts, src/screens/updatePlanItem/PlanItemLector.tsx, src/screens/updatePlanItem/UpdatePlanItemScreen.tsx
Resolves #79 
- add logic to PlanItem to save on-off state of lector
=> Handle lector on&off in PlanItem

README.md
=> Deleted a link to Guide.md that does not exist

src/components/TextInput.tsx, src/locale/en.ts, src/locale/pl.ts, src/screens/planActivity/PlanForm.tsx, src/screens/studentSettings/StudentSettingsScreen.tsx
=> 149 Edit student name

src/components/ModalTrigger.tsx, src/components/index.tsx, src/locale/en.ts, src/locale/pl.ts, src/navigators/MainStackNavigator.tsx, src/screens/index.tsx, src/screens/planItemActivity/ImageAction.tsx, src/screens/planItemActivity/ImageLibraryScreen.tsx, src/screens/planItemActivity/ImagePicker.tsx, src/screens/planItemActivity/PlanItemSimpleTask.tsx
=> Modal for image picker 

src/models/Plan.tsx, src/models/PlanItem.tsx, src/models/SubscribableModel.ts, src/screens/planActivity/PlanActivityScreen.tsx, src/screens/planItemActivity/PlanItemTaskScreen.tsx
Need to open new PR because of big changes since then (#132 )
=> #98: Add order parametr to PlanItem and sorting by order

src/components/CheckboxInput.tsx, src/models/PlanItem.tsx, src/screens/planActivity/TableRow.tsx, src/screens/planActivity/__tests__/__snapshots__/TableRow.test.tsx.snap, src/screens/planActivity/__tests__/__snapshots__/TaskTable.test.tsx.snap
Resolved: #75 for simple task. Complex task in not implemented yet.
=> #75: Add posibility to set task as done or not done

package.json, src/screens/planActivity/PlanActivityScreen.tsx, src/screens/planActivity/PlanForm.tsx, src/screens/planActivity/__tests__/PlanForm.test.tsx, src/screens/planActivity/__tests__/__snapshots__/PlanActivityScreen.test.tsx.snap, yarn.lock
Disable shuffle button for the plan's items if there are less than or equal to 1 not completed items on list.
=> #158: Disable shuffle button for the plan's items.

src/locale/en.ts, src/locale/pl.ts, src/screens/studentSettings/StudentSettingsScreen.tsx
=> #161 Delete student

android/build.gradle, src/models/Plan.tsx, src/screens/planActivity/PlanActivityScreen.tsx
Fix validation when we change an icon of a plan.
=> #204 Fix plan validation

src/components/StudentListElement.tsx, src/models/User.tsx, src/screens/dashboard/DashboardScreen.tsx
The PR resolves [https://github.com/autyzm-pg/friendly-plans-react/issues/196](#196) , information about currently selected student is persistent
=> Preserve information about selected student

ios/Podfile.lock, src/__mocks__/react-native-draggable-flatlist.tsx, src/__mocks__/react-native-gesture-handler/Swipeable.tsx, src/locale/en.ts, src/locale/pl.ts, src/screens/planItemActivity/PlanItemTaskScreen.tsx, src/screens/studentPlanList/StudentPlanListItem.tsx, src/styles/palette.tsx, tslint.json
Resolves #251 
Resolves #274 
Resolves #243
=> 251 delete plan

src/locale/en.ts, src/locale/pl.ts, src/screens/studentSettings/StudentSettingsScreen.tsx
=> Remove student confirmation

src/locale/en.ts, src/locale/pl.ts, src/screens/planActivity/PlanActivityScreen.tsx, src/screens/planActivity/PlanForm.tsx, src/screens/planActivity/__tests__/PlanForm.test.tsx, src/screens/planActivity/__tests__/__snapshots__/PlanActivityScreen.test.tsx.snap, src/screens/planItemActivity/PlanItemForm.tsx, src/screens/planItemActivity/PlanItemTaskScreen.tsx, src/screens/studentPlanList/StudentPlanList.tsx
=> Plan and Task default names

ios/Podfile.lock, package.json, src/components/ModalTrigger.tsx, src/components/Slider.tsx, src/components/index.tsx, src/locale/en.ts, src/locale/pl.ts, src/models/PlanItem.tsx, src/screens/planActivity/__tests__/__snapshots__/TaskTable.test.tsx.snap, src/screens/planItemActivity/PlanItemForm.tsx, src/screens/planItemActivity/SimpleTask.tsx, src/screens/planItemActivity/TimeSlider.tsx, yarn.lock
=> #273 set timer as slider

src/locale/pl.ts, src/screens/studentPlanList/EmptyStudentPlans.tsx
Set default plan number to 0 when student does not have any plan yet to avoid undefined in first plan name
=> #247: Set default plan number to 0

src/screens/planActivity/PlanActivityScreen.tsx, src/screens/planActivity/PlanForm.tsx, src/screens/planActivity/ShuffleButton.tsx, src/screens/planActivity/__tests__/__snapshots__/PlanActivityScreen.test.tsx.snap
I've created shuffle functionality using Knuth algorithm. It's working but shuffling process is visible for user due to usage of react-native-draggable-flatlist.
=> #170 Created shuffle tasks functionality

src/components/Slider.tsx, src/models/PlanItem.tsx, src/screens/planActivity/PlanForm.tsx, src/screens/planActivity/TableRow.tsx, src/screens/planActivity/__tests__/__snapshots__/TableRow.test.tsx.snap, src/screens/planItemActivity/PlanItemForm.tsx, src/screens/planItemActivity/PlanItemTaskScreen.tsx, src/screens/planItemActivity/SimpleTask.tsx, src/screens/planItemActivity/TimeSlider.tsx
I've added saving time according to timer. Also I've initialized slider according to saved time.
=> #273 Added saving time according to timer

src/screens/planActivity/TableRow.tsx, src/screens/planActivity/__tests__/__snapshots__/TableRow.test.tsx.snap, src/screens/planItemActivity/PlanItemForm.tsx
I've created time info on table row and also counting subtasks if it's complex task. If it's simple - info about subtasks is hidden.
=> #249 Info about Plan Elements time for simple task
